def generate_phoneme_feedback(phoneme):
    feedback = {
        's': "Place the tip of your tongue close to the ridge behind your upper front teeth. Let the air flow out with a hissing sound.",
        't': "Place the tip of your tongue against the ridge behind your upper front teeth. Release the air quickly to produce the 't' sound.",
        'r': "The 'r' sound can be tricky. Curl the tip of your tongue slightly without touching the roof of your mouth. Practice by saying 'red' and 'run'.",
        'l': "Place the tip of your tongue against the ridge behind your upper front teeth. Let the air flow around the sides of your tongue.",
        'g': "The 'g' sound is made by raising the back of your tongue to the soft part of the roof of your mouth. Practice with words like 'go' and 'get'.",
        'd': "Place the tip of your tongue against the ridge behind your upper front teeth. Let the air come out as you move your tongue away.",
        'k': "Raise the back of your tongue to touch the soft part of the roof of your mouth, then release the air.",
        'f': "Place your top front teeth lightly on your lower lip and blow air out.",
        'v': "Place your top front teeth lightly on your lower lip and voice out.",
        'b': "Bring both lips together and release air to make the 'b' sound.",
        'p': "Bring both lips together and release air quickly to make the 'p' sound.",
        
        'm': "Press your lips together and hum to make the 'm' sound.",
        'n': "Place the tip of your tongue against the ridge behind your upper front teeth and hum to make the 'n' sound.",
        'ʃ': "Place the tip of your tongue close to the ridge behind your upper front teeth, but slightly further back than for 's'. Let the air flow out with a hissing sound.",
        'ʒ': "Place the tip of your tongue close to the ridge behind your upper front teeth, but slightly further back than for 's'. Voice out to produce the sound.",
        'θ': "Place the tip of your tongue against your upper front teeth and blow air out.",
        'ð': "Place the tip of your tongue against your upper front teeth and voice out.",
        'ʧ': "Combine the 't' and 'ʃ' sounds. Place the tip of your tongue against the ridge behind your upper front teeth, then move it slightly back and release the air.",
        'ʤ': "Combine the 'd' and 'ʒ' sounds. Place the tip of your tongue against the ridge behind your upper front teeth, then move it slightly back and voice out.",
        'ŋ': "Place the back of your tongue against the soft part of the roof of your mouth and hum.",
        'j': "Raise the middle part of your tongue close to the roof of your mouth and voice out.",
        'h': "Blow air through your vocal cords without vibrating them.",
        'a': "Open your mouth wide and keep your tongue relaxed at the bottom.",
        'e': "Raise your tongue slightly towards the roof of your mouth and smile.",
        'i': "Raise your tongue high towards the roof of your mouth and smile.",
        'o': "Round your lips and push them slightly forward.",
        'u': "Round your lips and push them slightly forward while raising the back of your tongue.",
        'æ': "Open your mouth wide and place your tongue low and forward.",
        'ʌ': "Open your mouth slightly and keep your tongue relaxed at the bottom.",
        'ɔ': "Open your mouth wide and round your lips.",
        'ɪ': "Raise your tongue slightly towards the roof of your mouth.",
        'ɛ': "Raise your tongue slightly towards the roof of your mouth and smile.",
        'ə': "Relax your mouth and tongue.",
        'ʊ': "Raise the back of your tongue towards the roof of your mouth.",
        'ɒ': "Open your mouth wide and keep your tongue relaxed at the bottom.",
        'ɑ': "Open your mouth wide and keep your tongue relaxed at the bottom.",
        'ʔ': "Briefly stop the airflow by closing your vocal cords.",
        'w': "Round your lips and voice out.",
        'z': "Place the tip of your tongue close to the ridge behind your upper front teeth. Let the air flow out with a buzzing sound.",
        'ʁ': "Raise the back of your tongue close to the roof of your mouth and voice out.",
        'ɲ': "Place the tip of your tongue against the ridge behind your upper front teeth and hum to make a nasal sound.",
        'ç': "Raise the front of your tongue close to the roof of your mouth and blow air out.",
        'x': "Raise the back of your tongue close to the roof of your mouth and blow air out.",
        'ɣ': "Raise the back of your tongue close to the roof of your mouth and voice out.",
        'ɬ': "Place the tip of your tongue close to the ridge behind your upper front teeth and let the air flow around the sides of your tongue.",
        'ɮ': "Place the tip of your tongue close to the ridge behind your upper front teeth and voice out, letting the air flow around the sides of your tongue.",
        'ʍ': "Round your lips and blow air out without voicing.",
        'ɾ': "Quickly tap the tip of your tongue against the ridge behind your upper front teeth.",
        'ɽ': "Curl the tip of your tongue back and quickly tap it against the roof of your mouth.",
        'ɸ': "Place your top front teeth lightly on your lower lip and blow air out.",
        'β': "Place your top front teeth lightly on your lower lip and voice out.",
        'ħ': "Raise the back of your tongue close to the roof of your mouth and blow air out without voicing.",
        'ʕ': "Raise the back of your tongue close to the roof of your mouth and voice out.",
        'ɱ': "Place your top front teeth lightly on your lower lip and hum.",
        'ɬ': "Place the tip of your tongue close to the ridge behind your upper front teeth and let the air flow around the sides of your tongue.",
        'ɮ': "Place the tip of your tongue close to the ridge behind your upper front teeth and voice out, letting the air flow around the sides of your tongue.",
        # Add more phoneme feedback as needed
    }
    return feedback.get(phoneme.lower(), "No specific feedback for this phoneme.")
